sudo: required
env: 
  - YARN_GPG=no
services:
  - docker

before_install: 
  - docker build -f Dockerfile.dev -t gd00141/docker-react .

script:
  - docker run gd00141/docker-react npm run test -- --coverage