language: generic
sudo: required

services:
  - docker

#before_install: 
#  - docker build -f Dockerfile.dev -t gd00141/docker-react .

#this part was causing the ci to stuck and doplyment does not even start.
#script:
#  - docker run gd00141/docker-react npm run test -- --coverage 

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-951601701990"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  skip_cleanup: true