language: generic
sudo: required

services:
  - docker

before_install: 
  - docker build -f Dockerfile.dev -t gd00141/docker-react .

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-951601701990"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: AKIA53D7BURTPW4YYSFW
  secret_access_key:
    secure: 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